language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"

script:
    - DEBUG=1 nosetests -s

after_success:
    - pip install coveralls
    - DEBUG=1 coverage run --source=flask_oauthlib setup.py -q nosetests
    - coveralls

branches:
  only:
    - master

notifications:
    email: false
